baseURL = "https://www.sandyman.dev"
title = "Sandyマンのブログ"
paginate = 8
theme = "PaperMod"
enableRobotsTXT = true
enableGitInfo = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-8S0XGNJ553"
pygmentsUseClasses = true
hasCJKLanguage = true

[context.production.environment]
HUGO_VERSION = "0.92.2"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Sandyマンのブログ"
description = "技術系の記事とか競馬の記事とかなんでも書いてます。"
keywords = [ "ブログ", "競馬", "プログラミング" ]
author = "Sandyマン"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "https://lh3.googleusercontent.com/pw/AL9nZEXcibiTiJZ13XQyvylkB8zAI5XYuXP4rUW5XCSP7cOCQm11bcp6p1BGmVYuOQKiw0R9O9TVjX5AjRmOQPyx3cbQRXQkrRROkh7ze41-g8qYiExGr0lnEpmrC1N0DROav89-rxprYFysXe-XwNPjIhxTUA=s100-no?authuser=0"
  favicon16x16 = "https://lh3.googleusercontent.com/pw/AL9nZEXcibiTiJZ13XQyvylkB8zAI5XYuXP4rUW5XCSP7cOCQm11bcp6p1BGmVYuOQKiw0R9O9TVjX5AjRmOQPyx3cbQRXQkrRROkh7ze41-g8qYiExGr0lnEpmrC1N0DROav89-rxprYFysXe-XwNPjIhxTUA=s100-no?authuser=0"
  favicon32x32 = "https://lh3.googleusercontent.com/pw/AL9nZEXcibiTiJZ13XQyvylkB8zAI5XYuXP4rUW5XCSP7cOCQm11bcp6p1BGmVYuOQKiw0R9O9TVjX5AjRmOQPyx3cbQRXQkrRROkh7ze41-g8qYiExGr0lnEpmrC1N0DROav89-rxprYFysXe-XwNPjIhxTUA=s100-no?authuser=0"
  apple_touch_icon = "https://lh3.googleusercontent.com/pw/AL9nZEXcibiTiJZ13XQyvylkB8zAI5XYuXP4rUW5XCSP7cOCQm11bcp6p1BGmVYuOQKiw0R9O9TVjX5AjRmOQPyx3cbQRXQkrRROkh7ze41-g8qYiExGr0lnEpmrC1N0DROav89-rxprYFysXe-XwNPjIhxTUA=s100-no?authuser=0"
  safari_pinned_tab = "https://lh3.googleusercontent.com/pw/AL9nZEXcibiTiJZ13XQyvylkB8zAI5XYuXP4rUW5XCSP7cOCQm11bcp6p1BGmVYuOQKiw0R9O9TVjX5AjRmOQPyx3cbQRXQkrRROkh7ze41-g8qYiExGr0lnEpmrC1N0DROav89-rxprYFysXe-XwNPjIhxTUA=s100-no?authuser=0"

  [params.label]
  icon = "/images/logomark.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "/posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Sandyマンのブログ"
  Content = "プログラミングから競馬までなんでも書いてます。プログラミングはPythonやJavaScript中心にやってます。"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/sandyman_linux"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/SuperSandyman"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://youtube.com/@sandyman_linux"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "Scraps"
name = "Scraps"
url = "/scraps/"
weight = 20

[[menu.main]]
identifier = "Zenn"
name = "Zenn"
url = "https://zenn.dev/sandyman"
weight = 20

[markup.highlight]
noClasses = false
